# Generated by Django 5.2.7 on 2025-11-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
