# Generated by Django 5.2.7 on 2025-12-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_image_productcolor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('White', 'White'), ('Black', 'Black')], default='White', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('product_id', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='productcolorsize',
            unique_together={('color_id', 'size')},
        ),
    ]
