# Generated by Django 5.2.7 on 2025-12-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productcolor_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Purchases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
