# Generated by Django 5.2.7 on 2025-12-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_color_alter_order_image_alter_order_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
