# Generated by Django 5.2.7 on 2025-12-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_userorders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.userorders'),
        ),
    ]
