# Generated by Django 5.2.7 on 2025-12-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('processing', 'Processing'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
    ]
