# Generated by Django 5.2.7 on 2025-12-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Canceled'), ('processing', 'Processing'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
    ]
