# Generated by Django 5.2.7 on 2025-12-24 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_user_userorders_order_user_orders'),
        ('payment', '0005_remove_payment_order_payment_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='orders',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.userorders'),
        ),
    ]
