# Generated by Django 5.2.7 on 2025-12-24 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_userorders_user'),
        ('payment', '0006_alter_payment_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='orders',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.userorders'),
        ),
    ]
